[package]
name = "powercycle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mod_exp = "1.0.1"
primes = "0.3.0"
rand = "0.8.5"
